# Generated by Django 4.1.4 on 2022-12-31 18:45

from django.db import migrations


def create_groups(apps, schema_migration):
    User = apps.get_model('authentication', 'User')
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    add_ticket = Permission.objects.get(codename='add_ticket')
    change_ticket = Permission.objects.get(codename='change_ticket')
    delete_ticket = Permission.objects.get(codename='delete_ticket')
    view_ticket = Permission.objects.get(codename='view_ticket')

    creator_permissions = [
        add_ticket,
        change_ticket,
        delete_ticket,
        view_ticket,
    ]

    creators = Group(name='creators')
    creators.save()


    creators.permissions.set(creator_permissions)
    
    subscribers = Group(name='subscribers')
    subscribers.save()
    subscribers.permissions.add(view_ticket)

    for user in User.objects.all():
        if user.role == 'CREATOR':
            creators.user_set.add(user)
        if user.role == 'SUBSCRIBER':
            subscribers.user_set.add(user)
        
class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_follows_user_role'),
    ]

    operations = [
        migrations.RunPython(create_groups)
    ]
