# Generated by Django 4.1.4 on 2023-01-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='image',
            field=models.ImageField(blank=True, default='media/no-image-icon-23485.png', null=True, upload_to=''),
        ),
    ]
